git:
    depth: 1

language: java

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe -y
    - mkdir -p ~/.haxe/lib
    - echo ~/.haxe/lib | haxelib setup


script:
    - haxe build.hxml