git:
    depth: 1

language: haxe
haxe:
  - "3.2.0"
hxml:
  - build.hxml
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/812dfd281a82150998d7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
    
sudo: false
